### ISSUE TITLE
device_tracker for out-of-range devices don't recover after restart

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#121]
Jaymunro noted:
I have found the new code restores updates on the area and distance sensors when the device returns home, even after a HA restart. However if there is a restart, the device_tracker **also** goes unavailable but does not recover when the device returns home. A Bermuda reload is required while the device is home.

_Originally posted by @jaymunro in https://github.com/agittins/bermuda/issues/99#issuecomment-1970250356_
           

I think to replicate:
- out-of-range (unplug) a device that is being tracked
- restart HA
- note state of device_tracker entity
- power-up / in-range device
- note state of device_tracker entity does *not* update
- after reload of Bermuda, device_tracker resumes updating.

Work out why. Fix it.

**Comment by jaymunro** [comment]
Yes, those steps to replicate accurately describe the issue as I see it.

**Comment by agittins** [comment]
These issues should be resolved with #127 and the v0.5.0 release made tonight. I was doing some weird stuff during initialisation that I think I have a slightly better handle on now. Repeated reloads seem to work, as do reconfigurations and full HA restarts.
