### ISSUE TITLE
Changing Area of a scanner does not get reflected in Bermuda

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#137]
v0.5.1

## Describe the bug

Reported by Adizanni at https://community.home-assistant.io/t/bermuda-bluetooth-ble-room-presence-and-tracking-custom-integration/625780/59?u=agittins
> Another question, how to refresh the name and or area assignement when a scanner is moved to another area ?

It looks like the `area_name` and `area_id` are being persisted in `CONFDATA_SCANNERS` and the mechanism that's meant to freshen it isn't working.

Reload and [re]Configure both failed to apply a change in scanner area.

**Comment by agittins** [comment]
With PR #140 updating the Area on a scanner device (esphome unit etc) will take effect, and will do so immediately, no reload or restart required.

**Comment by jimtrout87** [comment]
I am having problems with this same issue, I'm running v0.7.4

**Comment by agittins** [comment]
HA has two devices for each esphome scanner now, the one in the esphome integration and the one in the Bluetooth integration. 

Bermuda uses the one from Bluetooth if it has been set, and uses the esphome device's entry otherwise. 

I think in current ha release, the Bluetooth integration now copies the area from the esphome integration, but i don't know if it then stores it, or if it re-copies at each startup or on changes.

The end result is that you probably need to change the area in the Bluetooth integration, and then Bermuda should see that change immediately.

**Comment by jimtrout87** [comment]
Thanks for the quick reply - it was in BLE i had not changed it and once i updated it, all sorted. Much appreciated!
