### ISSUE TITLE
Log spamming "Using freshest advert but it's still too old!"

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#138]
From https://community.home-assistant.io/t/bermuda-bluetooth-ble-room-presence-and-tracking-custom-integration/625780/62?u=agittins

> Scott8586 Scott Presnell
> I’m using the current version, 0.5.1, and I’m seeing a constant stream of this in my log file (e.g. more than one a second):
>
> `2024-03-20 20:22:56.040 WARNING (MainThread) [custom_components.bermuda] Using freshest advert but it's still too old!`
>
> Any hints on debugging this further?

Suspect we're copying the wrong source device's data to metadevice, and should be checking for a "fresher" one (or the last_seen stamp is being updated from somewhere else).

## initial response

Thanks Scott, I think it might be a logic error on my part - this will happen for iBeacons where Bermuda has chosen the "wrong" source address to copy some metadata from, or if the iBeacon's timestamp is somehow updated from some other source. All of this is internal to Bermuda though, so not a configuration issue on your end. 

Any given iBeacon might have multiple MAC addresses advertising it, typically because devices randomise their MACs for privacy, so there should be a single "current" source mac. It looks like Bermuda is choosing an "older" source mac, so the timestamps on that device's advertisements are older than the "last-seen" stamp on the beacon.

The other possibility is that I'm updating the timestamp on the beacon's record from somewhere other than the most recent source device.

Do you have a local bluetooth device attached to your HA machine? If you have bluetooth proxy devices, are they esphome or Shelly Plus units?

I should have a chance in the next 24 hours or so to take a proper look at this, and will hopefully have a release to fix it soon.

**Comment by Scott8586** [comment]
I don't have a Shelly, but I was using the local bluetooth device - I disabled it and restarted, and the log spam stopped.
