### ISSUE TITLE
"Invalid handler specified" error when installing through HACS

### ISSUE THREAD

**Issue by Sappher** [agittins/bermuda#232]
## Version of the custom_component

v0.6.7

## Configuration
-

## Describe the bug

Installed the repository through HACS and when I try to add the integration (after HA restart) I get an error:

Error occurred loading flow for integration bermuda: cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

## Debug log

```text

Logger: homeassistant.config_entries
Source: config_entries.py:2444
First occurred: 18:50:57 (21 occurrences)
Last logged: 19:02:29

Error occurred loading flow for integration bermuda: cannot import name 'EventStateChangedData' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)

```

HA version info:
Core
2024.3.0
Frontend
20240306.0

**Comment by agittins** [comment]
I think this is due to the older version of HA that you are running, I think `EventStateChangedData` was added in April.

Are you able to update to the current release of HA?

**Comment by Sappher** [comment]
Thank you, I was suspecting that but couldn't find the information about EventStateChangedData, so didn't want to go through blindly updating my HA version. But yes, I can update of course, thank you! This issue can be set to solved (I'll let you decide on that so will leave it open :))

**Comment by agittins** [comment]
Great, if you run in to any troubles let me know, but that part at least should be solved with an update.
