### ISSUE TITLE
Feature Request: Integrate macvendors.com API for MAC Address Manufacturer Lookup in Bermuda

### ISSUE THREAD

**Issue by jleinenbach** [agittins/bermuda#257]
**Title: Integrate macvendors.com API for MAC Address Manufacturer Lookup in Bermuda**

---

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I see a MAC address in my Home Assistant but cannot easily identify the device manufacturer. This makes it difficult to quickly recognize and manage devices on my network.

**Describe the solution you'd like**
I would like to see an integration of the API from macvendors.com into Bermuda. This would allow Bermuda to display the manufacturer name for devices based on their MAC address. For privacy reasons, only the first three hexadecimal values of the MAC address should be sent to the API (e.g., `https://api.macvendors.com/FC-A1-3E`), which is sufficient to determine the manufacturer and avoids sending the full MAC address.

**Describe alternatives you've considered**
- Manually looking up MAC addresses on websites like macvendors.com, which is time-consuming and inefficient.
- Using local databases for MAC address lookups, but they may not be as up-to-date as the online API.

**Additional context**
Integrating this feature will enhance user experience by providing quick and easy identification of devices. However, it's important to highlight potential privacy concerns and ensure users are aware of the data being sent. Only transmitting the first three hexadecimal values of the MAC address mitigates these concerns while still providing useful information.

URL: [https://macvendors.com/api](https://macvendors.com/api)

**Comment by agittins** [comment]
This would definitely be handy.

I sort of feel like it should be a separate integration in HA, and then it could maintain a central cache of records that other integrations like Bermuda could use. The API is limited to 1000req/day at a rate of 1req/second. So to be helpful in (say) Bermuda's 'Add devices' list we couldn't wait for it to query all the prefixes when the user clicks the button (at one prefix per second) so instead we'd have to look up prefixes as they appear, rate-limit ourselves to 1/s, and store the results locally, ready for when a user wants to look at them.

This is certainly do-able, and I think would be a great addition, but it feels a bit outside of Bermuda's scope. If someone created an integration to do this I would *definitely* be interested in integrating with it, but the effort required to do it well is more work than I'm ready to put into that versus some other key features for Bermuda. I'd consider it if I ran out of other goals :-)

It looks like core used to have this for ble device tracker but removed it: https://github.com/home-assistant/core/pull/13788 - looking at the diff there might give someone a great head-start on writing a custom integration themselves.

Another possibility to consider is to see if anyone has written a user-script for it, at least that way your browser could offer a right-click or tool-tip lookup of the info. Not ideal, but might remove a small part of the annoyance.

I'm going to close this as out of scope / not planned, but feel free to raise an issue if there's an integration I can integrate with to provide it.

**Comment by bartgrefte** [comment]
Due to the large amount of unrecognized devices (devices shown like `[00:24:3D:**:**:**] bermuda_00_24_3D_**_**_**` in de list) I thought I'd post a request about implementing a MAC vendor lookup function.

Seems there was already a request :)

"but feel free to raise an issue if there's an integration I can integrate with to provide it."
Tried finding one, so far no luck.
