### ISSUE TITLE
[Request] Implement a configurable cut-off for signal strength (`min_rssi`)

### ISSUE THREAD

**Issue by jeremysherriff** [agittins/bermuda#264]
**Is your feature request related to a problem? Please describe.**
I track my cat, and I find that she is often reported to be a location when she is actually outside but still near to the BLE receiver, eg sitting on the fence or in a tree near to the house.

**Describe the solution you'd like**
I would like a configurable minimum signal strength setting, in order to tune detection accuracy.
This would be very similar to the ESPHome `min_rssi` setting of the [ble_presence binary sensor](https://www.esphome.io/components/binary_sensor/ble_presence.html)

This value would need to be configurable per device being tracked, as different use-cases would require different values to be considered home vs away.

**Describe alternatives you've considered**
I cannot think of any alternatives

**Additional context**
When she is outside, the `Nearest RSSI` value reported is around -94, as opposed to -81 when she is inside in the same room. My cut-off value would likely be around -88 in this instance.

**Comment by Rembock** [comment]
I've just solved a similar problem by placing some sort of faraday cage behind the scanner. In my case I had 2 scanners on either side of a thin wall, this caused my recievers to hop from one area to the other. Now as a test I placed some aluminum foil behind 1 scanner and everything seems stable. This might also help you block your cat's signal outside.
Alternatively, you could also possibly play around a bit with the max radius.

**Comment by jeremysherriff** [comment]
Thanks for the suggestion, the max radius is a functional equivalent and I have overlooked that.
I will experiment with numbers and see how I go.

I believe you can **Close as not planned** at this stage (I can only Close with comment)

**Comment by agittins** [comment]
Downside of course is that `max_radius` is global, but it might do what you need.

I am hopeful we'll have full trilateration "soon", which will ultimately give you much better options, but that's not a lot of help in the interim :-) 

I'll probably close as not planned as you suggest, but you've definitely planted a seed in my mind. I think your use-case is a solid one, but I'm not sure I'd want to solve it by ignoring by signal level (or a single range measurement). I'll let the idea rattle about in my head for a bit before I do. Your issue has won the creation of a new status label: **cogitating** ! 😅 

I LOVE @Rembock's faraday cage solution! 🤣 It's a clever physical work-around!

**Comment by jeremysherriff** [comment]
> Your issue has won the creation of a new status label: cogitating !

Yay! (?)

Everything's died on my side, I'm getting no data and seeing no devices - am currently pulling diag data and debug logs but this does not look good:
![image](https://github.com/user-attachments/assets/fcec77ba-0087-42a7-86fb-be2c1e9e19bd)

**Comment by agittins** [comment]
@jeremysherriff yikes! Someone else seems to have seen the same thing happen on theirs, reported at #235.

Can you see if doing a `reload integration` restores the sensors?

If you could also do a `download diagnostics` while it's working, and then if it stops working do another one, and send me both files, so I get a before-and-after picture of things?

If you could join in on #235 with that so I can track it there that would be great.

After a little cogitation((!) I've decided that I will close this issue, as I think that for the moment the `max_radius` setting is probably the best way to address the use-case until we have trilateration sorted out.
