### ISSUE TITLE
[0.6.9rc2] Per-Scanner config is not retained between configuration sessions

### ISSUE THREAD

**Issue by jeremysherriff** [agittins/bermuda#290]
## Version of the custom_component
0.6.9 rc1 and rc2

## Configuration
Not relevant

## Describe the bug

When entering the **Calibration 2: Per-Scanner** settings, all scanners are shown as having 0 as an offset, whether a previous configuration has been made or not.
E.g.;
```
BT Proxy Living Room: 0
hci0 (0A:62:26:22:14:36): 0
BT Proxy Bedroom: 0
BT Proxy Office: 0
BT Proxy Guest Brm: 0
BT Proxy Garage: 0
```
despite me previously configuring hci0 to -7

## Debug log

Not relevant I think

**Comment by jeremysherriff** [comment]
Feedback on 0.6.9 & the per-scanner configuration:
The per-scanner configuration is working pretty well for me, the device I am tracking is very poor quality so it is difficult for me to comment on the actual outcomes reliably but it certainly seems much improved with using a decent negative offset for the USB dongle.

**Comment by agittins** [comment]
rc2 is using a different key for the offset config, so if you saved it in rc1 it won't appear in rc2, but making a new setting should stick - does that mirror what you're seeing?

**Comment by jeremysherriff** [comment]
oh sorry, I didn't double-check after upgrading to rc2. It appears to save and display the retained settings correctly now!
Definitely an issue on rc1, but resolved in rc2.

**Comment by agittins** [comment]
Awesome, cheers!
