### ISSUE TITLE
How to find Bluetooth device identifiers

### ISSUE THREAD

**Issue by ahmet8282** [agittins/bermuda#313]
No matter how many scanner apps I tried, the identifier listed on the apps do not match what bermuda finds through bluetooth proxy. How do people find it? I have dozens of devices listed and I can not find what is what. 

Same with iphone identifier. None of the tutorials about finding the identifier through mac os x keychain seem to work. 

I am so close to make BLE scanners work but I can not distinguish devices

**Comment by agittins** [comment]
Hi Ahmet, could you provide some screenshots so I can better understand what you're seeing?

Some devices will only appear with their Mac address (like 00:54:ea:2f:44:3a) while others will have a name.

iBeacons will show up with their uuid which is a long hex string. 

Let's start by concentrating on a single device, if you can show me how it shows up in a scanner app, and what you see in the Bermuda "add devices" list, we can go from there. 

If you can also include the output of "download diagnostics" that will help a lot. Bear in mind it can take a while for the diagnostics to download. 
![17280272988412809783579494854912](https://github.com/user-attachments/assets/2087d2f8-6edb-4fcb-af53-d3773a61a0ef)

**Comment by klim123123** [comment]
> then my iphone.

for iphones i used method from espresense
https://espresense.com/beacons/apple
it's just works with Bermuda.

**Comment by klim123123** [comment]
> The enroll button with espresense screen doesnt exist anymore. How did you do it?

You need to install espresense, get all the IRK for iphone and save them. 
Then you can use in Bermuda.

**Comment by klim123123** [comment]
> Espresnse firmware and ble proxy firmware can not live side by side, right?
nope, they can't be on one device.
if you need to connect new devices very often, just leave espresnse on one esp32. esp32 devices are super cheap today.

**Comment by agittins** [comment]
The different ways to get the IRK are documented at https://github.com/agittins/bermuda/wiki/How-to-get-the-IRK-(Identity-Resolving-Keys)-for-iOS,-Android-etc

I do plan to come up with an esphome-native way to do it, but haven't got it fully solved yet.

Thanks for sending the screenshots showing your Tile device. I don't have any direct experience with these, but **most** BLE devices won't send any advertisements if they're currently connected to anything, and the tile app (or whatever you're using to view that info) will usually remain connected, AFAIK.

I think the Tiles have a feature where you can specifically enable "iBeacon" mode, where it will send broadcasts that will show up in Bermuda, and I *think* it will do that regardless of whether it's connected to your app or not (but I don't know for sure).

An easier way to start might be to install the HA companion app on a phone and enable the BLE Transmitter in that - this might give you a quick win and confirm that the rest of the stack is working OK, then you can tackle the tile and the IRK parts separately, perhaps.

**Comment by agittins** [comment]
It's 8th on the list in the email you sent me.

You're looking for:
![image](https://github.com/user-attachments/assets/293e7c2b-e0f7-496e-8c7b-6482471c7e8a)

Note that you can type in part of the mac address to filter the list while you're looking.
