### ISSUE TITLE
A option do change the location based on device

### ISSUE THREAD

**Issue by soloam** [agittins/bermuda#325]
**Is your feature request related to a problem? Please describe.**
In my home, for example, the location of the kitchen is a wall that also contains the living room shelly, so I have 2 shelly's, one for the kitchen and one for the living room next to each other. I have set both to each location (living room and kitchen), but now that makes "my" bermuda jump between kitchen and living room. I would like to keep the home assistant with the correct zones (this is important to all kinds of things like automations) but I would like to say to bermuda that the one that is from the kitchen, actually should assume the living room. Now I'm doing that with templates, but native it would be great!

**Describe the solution you'd like**
A option to override the zone by proxy

Thank you and great work.

**Comment by agittins** [comment]
Hmm. That's a tough one. I totally see your use-case, and agree that keeping them in their respective areas is important for the other functions those devices perform.

I don't think I will implement this as a feature though, as it's something that won't be needed once we have trilateration (#21) and it adds complexity to the code for a fairly narrow use-case.

- I think the templating fix you've come up with is probably the best way to address it. 

- Another option would be to use the calibration settings in v0.6.9rc2 to "turn down" the blueooth receiver in one of them so it never "wins" the area for a device.

- Another option would be to set the two shellys to both be in the same area, but change the area for the individual *entities* (switch, light, binary sensor etc) to be in the other area. That way both shellys will show in the kitchen, but you manually assign any switches, lights etc from that device to be in the area you want. (HA uses the device area by default to work out the area for each entity, but you can override that on a per-entity basis).

Once we have trilateration I expect most people will use that to work out the area, which won't have this particular issue. Does that sound fair?

**Comment by soloam** [comment]
Tks for the replay I didn't know you were working in tringulating the signal to determine the position! That is something that ESPresence does with a addon in home assistant and it's very cool! That would be perfect!

Thank you for your work

**Comment by agittins** [comment]
No worries, glad you're enjoying it!

Yes trilateration has been the main goal from the start but it's been a long time coming! A lot of work has gone into understanding the basics and trying to get a good user experience with the simple area matching.

I'll close this issue for now but please feel free to comment with further info etc.
