### ISSUE TITLE
Adding Shelly Plus 1 as sensor

### ISSUE THREAD

**Issue by crhammock** [agittins/bermuda#333]
Not sure if I am missing something I have followed what documentation I can find but can't get this working.

I have one Everything Presence Lite (ESP32) device working as a sensor just fine.  I also have 3 Shelly Plus 1 devices in Home Assistant.  The Shelly devices are configured as Active Bluetooth scanners.  I have also confirmed that the "aioshelly_ble_integration" script is enabled and running.  I am trying to track my Samsung S22 phone.  The UUID entity in Bermuda show the distance the phone is from each tracker which shows the shelly devices by name although only the EPLite device shows a distance the three shelly devices show as unknown at all times.

I have tried checking the logs on the shelly and although it shows a number of MACs being scanned I can't match them up to my phone as it is using a random MAC.  I think in the logs I can see the Shellys detecting each other MACs.

Am I missing something in my setup, is there something I have to do on the Shellys to the script?  Do I need to put the phone UUID somewhere on the Shelly devices?  Should this work?

**Comment by crhammock** [comment]
As is often the case, after spending hours trying to get something working and finally posting an issue in less than 1 hour after posting I was able to resolve the issue myself.

After reading posts on another forum it seemed the issue might be tied to the Shelly firmware version, although I had upgraded the firmware as part of the troubleshooting process I didn't realise the upgrades are incremental so I wasn't on the latest version.  One final upgrade to 1.4.4 on each Shelly device resolved my issue.  Hope this helps someone

**Comment by agittins** [comment]
> in less than 1 hour after posting I was able to resolve the issue myself.
Hey, that's great! The power of [rubber-ducking](https://en.wikipedia.org/wiki/Rubber_duck_debugging) :-) 

I'll add a note in the wiki then, hopefully it will help others in future.
