### ISSUE TITLE
Account for removing Scanners that exist but are no longer Scanners

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#345]
If a scanner no longer acts as a scanner, it still shows in the config flow diagnostics, with requisite skullybones.

Waiting for confirmation if this happens with both esphome and shelly.
Raised via convo at https://community.home-assistant.io/t/bermuda-bluetooth-ble-room-presence-and-tracking-custom-integration/625780/390?u=agittins

Also (only slightly) related to #214

**Comment by agittins** [comment]
(comments also indicate that reinstalling the integration in this case works, so there must be a visible difference for Bermuda to key from).

**Comment by mterry63** [comment]
ESPHome device that provided digital input/output devices to Home Assistant. Added BLE proxy config, reconsidered and removed the BLE proxy config. Device still performs input/output functions but now appears as dead in Bermuda and can't be removed.

**Comment by agittins** [comment]
I have pushed changes that should address this in PR#360 and created a release candidate with the fix in v0.7.1rc1 - please let me know if this solves the dead-proxy-hauntings :-)
