### ISSUE TITLE
Failed Start Up

### ISSUE THREAD

**Issue by dani-rodr** [agittins/bermuda#355]
## Describe the bug
The integration failed to start even when reloading. I was also noticing that my phone disconnects every 1 hour and 48 minutes, not sure if this was the integration or my device.

## Diagnostics

I found this error in the log

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/bermuda/bermuda_device.py:133
integration: Bermuda BLE Trilateration (documentation, issues)
First occurred: 10:56:57 AM (91 occurrences)
Last logged: 10:57:44 AM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/bermuda/coordinator.py", line 564, in _async_update_data
    device.calculate_data()
  File "/config/custom_components/bermuda/bermuda_device.py", line 133, in calculate_data
    scanner.calculate_data()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'calculate_data'

**Comment by dani-rodr** [comment]
I just had to reconfigure, though I saved a screenshot beforehand to easily re setup

**Comment by agittins** [comment]
Thanks for your report. I don't know what would have caused this, it seems a bit odd - but I've added a check to the next version that will work around it. Maybe it was a race condition while it is first setting up the integration.
