### ISSUE TITLE
Config was used from bermuda

### ISSUE THREAD

**Issue by codyc1515** [agittins/bermuda#368]
## Configuration

Started after upgrading to 2025.11.0

## Describe the bug

```
Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 21:23:28 (1 occurrences)
Last logged: 21:23:28

Config was used from bermuda, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'bermuda' custom integration
```

**Comment by agittins** [comment]
Hi Cody, thanks for your report!

I think we had an RC out by the 2024.11 release that fixed it, but probably not a full release version. At any rate, this should definitely be sorted in the current v0.7.1 release, but please re-open this if it crops up again. Cheers!
