### ISSUE TITLE
Device area doesn't change to "unknown" after device leaves all areas

### ISSUE THREAD

**Issue by GZ-3** [agittins/bermuda#371]
Hello everyone!
After updating to 0.7.0 the "device area" doesn't change from ROOM_NAME to "unknown" after going away as it was before the update, it just stays the same (ROOM_NAME). While the "Bermuda tracker" changes from "home" to "away" it was much more convenient as it was before for making automations.

EDIT: After updating to 0.7.1rc1devices started hopping from ROOM_NAME to "unknown" fast without physically moving while being near a transmitter. After downgrading to 0.6.8 everything returned to the way it was.

**Comment by sbeier23** [comment]
same here. downgrading to 0.6.8 helped.

**Comment by Kwull** [comment]
subscribed to the same issue :)

**Comment by agittins** [comment]
Hi all, thanks for your reports! 

Yes this seems to be a regression introduced somewhere between 0.6.9rc2 (I think) and the 0.7 series as a side-effect from other work. From my testing it seems to only apply to "metadevices" (which means: IRK (Private BLE Device) and iBeacon devices). It also appears to only affect the "Area" sensors and not the `device_tracker` sensors.

I should have a fix for it out soon. If anyone is seeing it happening to non-meta-devices (ie, those being tracked purely by MAC address) let me know, but my testing last night seemed pretty solid.

**Comment by af-77** [comment]
> Hi. Seems that 0.6.9rc3 still works.

Sorry. Wrong information :-(
With 0.6.9rc3 the problem also accurs.
Seems 0.6.9rc2 is the last "good" version.

Sorry for the confusion.

**Comment by ronaldheft** [comment]
@agittins Looking good on my end since the update. Thanks for the fix!

**Comment by agittins** [comment]
Excellent, thanks Ron!
