### ISSUE TITLE
Failed to find Scanner (local USB Bluetooth)

### ISSUE THREAD

**Issue by Chreece** [agittins/bermuda#386]
## Describe the bug

Just noticed, my logs are flooded with the following error:
```
Failed to find config for scanner A4:6B:B6:2F:46:5C, this is probably a bug. (373 previous messages suppressed)
Failed to find scanner hci0 (A4:6B:B6:2F:46:5C) (A4:6B:B6:2F:46:5C) in Device Registry (375 previous messages suppressed)
```
That's the bt adapter from host and it is available in the Bluetooth integration: 
![Screenshot_20241114_115532_Home Assistant](https://github.com/user-attachments/assets/296519b2-3933-44b8-ada9-bbf9bbe461bb)

And the config entry is also available: 
```
...
  "data": {
    "manager": {
      "adapters": {
        "hci0": {
          "address": "A4:6B:B6:2F:46:5C",
          "sw_version": "homeserver",
          "hw_version": "usb:v1D6Bp0246d0542",
          "passive_scan": false,
          "manufacturer": "Intel Corporate",
          "product": "0032",
          "vendor_id": "8087",
          "product_id": "0032"
        }
      },
...

      "scanners": [
        {
          "name": "hci0 (A4:6B:B6:2F:46:5C)",
          "start_time": 1649746.229855161,
          "source": "A4:6B:B6:2F:46:5C",
          "scanning": true,
          "type": "HaScanner",
          "last_detection": 1650251.908447104,
          "monotonic_time": 1650252.00044757,
          "discovered_devices_and_advertisement_data": [
            {
```

**Comment by agittins** [comment]
Hi Chris, thanks for the report. Which version of Bermuda are you running? Could you attach the output of "download diagnostics" as well? 

I thought I'd fixed this in v0.7.1 but maybe I'm still missing something.

**Comment by Chreece** [comment]
Hey 👋🏼,

I'm using the 0.7.1 tried also to redownload with no luck. 

Diagnostics file: 
[config_entry-bermuda-5f2c63e61e0fe1185cf0b44f654f1076.json](https://github.com/user-attachments/files/17748233/config_entry-bermuda-5f2c63e61e0fe1185cf0b44f654f1076.json)

**Comment by agittins** [comment]
Ha... well that's embarrassing. It's not working on my prod system either 😅 I'll sort it out.

**Comment by Chreece** [comment]
No prob, you have me something wonderful and helpful for free... Can't complain 😁

**Comment by agittins** [comment]
Latest release v0.7.2 should fix this now 👍🏼
