### ISSUE TITLE
Fail to Update from v0.6.8 then after removing integration fail to install 

### ISSUE THREAD

**Issue by pansament** [agittins/bermuda#388]
As title says I was unable to update from v0.6.8 an I tried to remove and install v0.7.2 and is stuck at rolling cercle.

Tried to restart HomeAssistant several times and try again. No Go. Tried to remove bermuda folder from custom_components and restart home assistant and try again with no luck... 
Tried to install v0.6.8 and is installing correctly. Tried again to update and every step writen above with no luck.

What m I missing? How can I install v0.7.2?

LE: After update HACS everything is working fine. Sorry for this opened issue.

**Comment by agittins** [comment]
> LE: After update HACS everything is working fine. Sorry for this opened issue.

Hi! Glad you got it working in the end, that's great. Generally if there's any problem updating it's worth trying to get it going through HACS, since sorting things out directly with the folders etc can get you into a bit of bother pretty quickly!

Great that you got it sorted out, enjoy!
