### ISSUE TITLE
Failed to find config for scanner

### ISSUE THREAD

**Issue by codyc1515** [agittins/bermuda#399]
## Configuration
HA 2024.12.0 beta

## Describe the bug

This error originated from a custom integration.

Logger: custom_components.bermuda
Source: custom_components/bermuda/log_spam_less.py:92
integration: Bermuda BLE Trilateration (documentation, issues)
First occurred: 10:57:03 (6 occurrences)
Last logged: 10:57:48

Failed to find config for scanner D8:3A:DD:E8:80:1C, this is probably a bug.
Failed to find scanner hci0 (D8:3A:DD:XXXXXX) (D8:3A:DD:XXXXXX) in Device Registry (1969 previous messages suppressed)
Failed to find config for scanner D8:3A:DD:XXXXXX, this is probably a bug. (1915 previous messages suppressed)
Failed to find scanner hci0 (D8:3A:DD:XXXXXX) (D8:3A:DD:XXXXXX) in Device Registry (433 previous messages suppressed)
Failed to find config for scanner D8:3A:DD:XXXXXX, this is probably a bug. (433 previous messages suppressed)

## Diagnostics

Redacted

**Comment by agittins** [comment]
Thanks for the report!

I just tried this on my dev system and I'm not getting the error. Are you running Bermuda v0.7.2? There was an update to how the scanners are looked up in the device registry in that version.

**Comment by codyc1515** [comment]
Appears to have been fixed by https://github.com/agittins/bermuda/commit/8f905a4000b5632b6a3971463775bacbeeed624d
