### ISSUE TITLE
BLE proxy is lost after power is disconnected

### ISSUE THREAD

**Issue by jonpaterson** [agittins/bermuda#416]
I have 3 ESP32-C3 devices.  They show correctly as proxies when the ESPHome software is updated on the device, but if you cut power to the device after this, it will not register again with Bermuda unless you perform a re-installation on the ESP32 device.  It seems as if Bermuda is not seeing or the device is not registering correctly as a sensor when it boots, only when the ESP32 software is updated.

I can replicate this issue consistently. Restarting HA does not cause the missing proxy to be seen, the re-installation of ESP32 seems to be the only resolution.

**Comment by agittins** [comment]
Hi! Thanks for your report. This is most likely an issue with the board or config and not a Bermuda (or homeassistant) issue. 

Please include the full esphome yaml that you are using, and verify you are using the recommended config options from the wiki.

**Comment by jonpaterson** [comment]
Hi Ashley, I thought about this more last night and started down the same path and you are correct.  I found the resolution you MUST install the initial image on the ESP32-C using USB to ensure that that esp-idf is correctly configured.  When I did this, with exactly the same configuration as previous all devices worked correctly.  You might want to underline this for the wiki as it worked perfectly for myself after making this process change for initial imaging.  

here is my working configuration

`esphome:
  name: office-ble
  friendly_name: Office BLE

esp32:
  board: esp32-c3-devkitm-1  # Feel free to use a more specific board if that's what you have
  framework:
    type: esp-idf  # This is important: the default "arduino" framework does not perform well.
    sdkconfig_options:
      # @grigi found in testing that these options resulted in better responsiveness.
      # BLE 4.2 is supported by ALL ESP32 boards that have bluetooth, the original and derivatives.
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      # Also enable this on any derivative boards (S2, C3 etc) but not the original ESP32.
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      # Extend the watchdog timeout, so the device reboots if the device appears locked up for over 10 seconds.
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

logger:
  baud_rate: 0  # 0 Enables logging, but disables serial-port logging to free CPU and memory

ota:
  platform: esphome

api:

  # Only enable BLE tracking when wifi is up and api is connected
  # Gives single-core ESP32-C3 devices time to manage wifi and authenticate with api
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  # Disable BLE tracking when there are no api connections live
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

esp32_ble_tracker:
  scan_parameters:
    # Don't auto start BLE scanning, we control it in the `api` block's automation.
    continuous: False
    
    active: True  # send scan-request packets to gather more info, like device name for some devices.

    interval: 320ms  # default 320ms - how long to spend on each advert channel
    window:   300ms  # default 30ms - how long to actually "listen" in each interval. Reduce this if device is unstable.
    # If the device cannot keep up or becomes unstable, reduce the "window" setting. This may be
    # required if your device is controlling other sensors or doing PWM for lights etc.

bluetooth_proxy:
  active: true  # allows outbound connections from HA to devices.

sensor:
  - platform: uptime
    # The uptime sensor is extremely helpful to know if your device is rebooting
    # when it shouldn't be. This might indicate your interval-to-window timing is
    # too tight, and the window needs to be reduced.
    name: "Uptime Sensor"
    update_interval: 60s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
`

**Comment by jonpaterson** [comment]
`esphome:
  name: office-ble
  friendly_name: Office BLE

esp32:
  board: esp32-c3-devkitm-1  # Feel free to use a more specific board if that's what you have
  framework:
    type: esp-idf 
    sdkconfig_options:
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

logger:
  baud_rate: 0  # 0 Enables logging, but disables serial-port logging to free CPU and memory

ota:
  platform: esphome

api:
  on_client_connected:
     - esp32_ble_tracker.start_scan:
        continuous: true
  on_client_disconnected:
    if:
      condition:
        not:
          api.connected:
      then:
        - esp32_ble_tracker.stop_scan:

esp32_ble_tracker:
  scan_parameters:
    continuous: False
    active: True 
    interval: 320ms  # default 320ms - how long to spend on each advert channel
    window:   300ms  # default 30ms - how long to actually "listen" in each interval. Reduce this if device is unstable.

bluetooth_proxy:
  active: true 

sensor:
  - platform: uptime
    name: "Uptime Sensor"
    update_interval: 60s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
`

**Comment by agittins** [comment]
That's great to hear! Did your boards come shipped with esphome on them already, or have you had them for a while? I think the flash partition change was over a year ago, but maybe there's something else that means more boards will require a USB flash to be stable.
