### ISSUE TITLE
Support identifying devices by UUID, possibly IRK

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#44]
For devices that don't have a static MAC, or who don't advertise their name it would be useful to ID them via the UUID they broadcast.

(user report from Steven @ <https://community.home-assistant.io/t/bermuda-bluetooth-ble-room-presence-and-tracking-custom-integration/625780/2> notes HA Companion app sending beacons has stable UUID but no name listed against MAC).

Check if best to integrate with iBeacon integration or with jc2k's <https://next.home-assistant.io/integrations/private_ble_device/> Private BLE Device integration rather than reinventing wheels (I think it only works with iOS currently).

- ~~assess if better to tie in with an existing integration~~ no for ibeacon, yes for IRK.
- ✔️ if not, split out the IRK/iOS parts and make this issue just about adding devices by UUID

**Comment by jaymunro** [comment]
For integrating with jc2k's https://next.home-assistant.io/integrations/private_ble_device/, the tracker sensors have an attribute `current address` that could be parsed to identify MACs.

However, I feel integrating the code would be cleaner from the user’s pov as their would be less jumping around between integrations to set up monitoring.

**Comment by agittins** [comment]
Note to self: see conversation 2023-11-20 04:20am with Jc2k re this.

It looks like a solid solution might be to listen for events that get fired by personal_ble_device, device_tracker and ibeacon integrations that advise when a known device has rotated to a new MAC. If that doesn't pan out, Jc2k is keen to help ensure the required info is available in the integrations, which would be a big plus to not have to take on maintaining those algo's myself. 

So essentially if a user configures an IRK for a device, I'd find out the current MAC for that device whenever it shows up, and can use that to track and display.

The `current_address` attribute on known IRK devices is probably enough to get going initially, too. My partner has an iPhone so might be able to test with that, but don't have time currently to mess about with MacOS etc to get the IRK, which.. irks me :-P

**Comment by blind-oracle** [comment]
Do I get it correctly that in the current integration state it's not possible to use devices with randomized MACs? E.g. HA Companion App

**Comment by jaymunro** [comment]
Correct. This one has some great potential but needs some TLC. I have no experience in developing an integration and would like to help standardise this so that at least the `device_tracker` methods start using more modern methods. As best I can tell, they are using a legacy method and as a result can't be renamed or further configured. Wanna help? I'm keen, but after viewing the code I'm a bit lost on the best path forward.

Once done, we should be able to do something similar to `Private BLE`.

**Comment by agittins** [comment]
FYI iBeacon UUID tracking support is now committed via #116 - I have some bugs to squash yet (errors thrown during config-flow) but it does work, so you can install it by choosing the `main` branch in HACS' `redownload` if you want to see the latest, if a little hacky, changes.

I hope to make a release including it soon, but want to sort out the errors it throws before doing that.

This solves tracking for the Android companion app and other iBeacon-sending apps. I can't see that the iOS app supports doing that (which seems odd) but if anyone knows of another iOS app that does support acting as an iBeacon, link us up!

Native IRK support via Private BLE Device will come later, I think I will split this issue to a new one to track IRK support.
