### ISSUE TITLE
device_tracker missing in UI and does not get renamed

### ISSUE THREAD

**Issue by jaymunro** [agittins/bermuda#58]
## Version of the custom_component

0.3.1

## Describe the bug

The device_tracker sensor is absent in the UI and also does not get renamed like the other two when the device is renamed.

<img width="1044" alt="Screenshot 2023-10-31 at 8 45 56 AM" src="https://github.com/agittins/bermuda/assets/1166024/4af1391e-e9a5-4774-9da0-406aa9ae7340">

<img width="661" alt="Screenshot 2023-10-30 at 6 51 42 PM" src="https://github.com/agittins/bermuda/assets/1166024/5ed45c54-ad8d-4f88-b540-5f49ae1908b0">

<img width="913" alt="Screenshot 2023-10-30 at 6 56 08 PM" src="https://github.com/agittins/bermuda/assets/1166024/0f6f783b-8837-4d6e-81af-ed844912cd98">

The related `device_tracker.bermuda_dc_2c_6e_12_fa_df` entity is not present in the registry however it does get listed in Developer tools > STATES
<img width="911" alt="Screenshot 2023-10-30 at 6 56 27 PM" src="https://github.com/agittins/bermuda/assets/1166024/495d9284-3c09-48cd-965f-9b8eb0b68931">

**Comment by jaymunro** [comment]
I see the following in line 572 of __init__.py
```
        TODO: Allow user to configure what name to use for the device_tracker.
```

**Comment by jaymunro** [comment]
Using https://github.com/home-assistant/core/tree/dev/homeassistant/components/private_ble_device as a reference, I see it has a dedicated `device_tracker.py` with
```
from homeassistant.components.device_tracker.config_entry import BaseTrackerEntity
from homeassistant.const import STATE_HOME, STATE_NOT_HOME
```
and a class `BasePrivateDeviceTracker(BasePrivateDeviceEntity, BaseTrackerEntity)`

I don't seem to find any `BaseTrackerEntity` in Bermuda. Should this be adapted?

**Comment by jaymunro** [comment]
Ah, at line 512 in `__init__.py`
```
            # Try to make a nice name for prefname.
            # TODO: Add support for user-defined name, especially since the
            #   device_tracker entry can only be renamed using the editor.
            if device.prefname is None or device.prefname.startswith(DOMAIN + "_"):
                device.prefname = (
                    device.name
                    or device.local_name
                    or DOMAIN + "_" + slugify(device.address)
                )
```

**Comment by jaymunro** [comment]
For a device (an Eve Motion) created with the original names set by the integration:

**/config/.storage/core.entity_registry**
```
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "94e5a656f49dfc58f3355df6a187aa6f",
        "device_class": null,
        "device_id": "73baf50fe95a07129d87807860eaea5c",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.eve_motion_d91b_distance",
        "hidden_by": null,
        "icon": null,
        "id": "e4dd6d6d196ced731ae26a21fb2495b9",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": "distance",
        "original_icon": null,
        "original_name": "Distance",
        "platform": "bermuda",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "fb:16:a8:31:f0:af_range",
        "unit_of_measurement": null
      },
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "94e5a656f49dfc58f3355df6a187aa6f",
        "device_class": null,
        "device_id": "73baf50fe95a07129d87807860eaea5c",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.eve_motion_d91b_area",
        "hidden_by": null,
        "icon": null,
        "id": "50246bcb49772213ca985943e38bc0c2",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": "bermuda__custom_device_class",
        "original_icon": null,
        "original_name": "Area",
        "platform": "bermuda",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "fb:16:a8:31:f0:af",
        "unit_of_measurement": null
      }
```

The `device_tracker.bermuda_fb_16_a8_31_f0_af` entity is **not present** in the registry however it does get listed in `Developer tools > STATES`

<img width="795" alt="Screenshot 2023-10-30 at 7 31 25 PM" src="https://github.com/agittins/bermuda/assets/1166024/cbeccffb-77a3-480c-8791-878fc1f3bcc1">

Does the fact that it is missing in the entity_registry mean that it is not being declared or created properly?

**Comment by agittins** [comment]
Thanks for the report and your time in digging into it!

> Does the fact that it is missing in the entity_registry mean that it is not being declared or created properly?

Yes, I think this is probably the answer :grinning: Do other device_tracker entities appear in the entity registry?

Currently all I do is fire the device_tracker "see" event. I don't know if the device_tracker integration actually supports the entity registry. Given how it uses the `known_devices.yaml` file I suspected it didn't but I must admit I didn't spend a long time looking as I was keen to move on to area-based tracking - I sort of concluded that the `device_tracker` integration was in a pretty "legacy" state (this might be a very incorrect assumption on my part) so I didn't want to spend much effort on it at the time.

Was there a reason you wanted to use the device_tracker for the motion sensor? I ask because device_tracker's only ability (afaik) is to indicate if a given *person* is at home or not at home. But a motion sensor might be better used to indicate that a given *area* is occupied or not occupied, which doesn't require Bermuda.

The way this works is that the device_tracker would be considered "home" as long as the motion sensor is present, regardless of whether it is triggered. That is, bermuda tells you if bluetooth *devices* are *present*, not if they have a particular state. Does that make sense?

I might be confused about your use-case though, so let me know if I'm missing something there.

That said, the renaming thing is probably something daft I'm doing :) I tried to let the integration use the device name if it gives us one, but that can come and go over time - and the way `device_tracker` stores everything in the yaml file meant I had to be careful about how I called the "see" service so it didn't create separate entities - I'll take a further look into the info you've gathered on that a little later (recovering from a cold currently so brain is not working optimally!)

**Comment by jaymunro** [comment]
Yes, all my device trackers are in `core.entity_registry` from iBeacon, Private BLE, iCloud, and various other integrations. But they are not in known_devices.yaml except the new bermuda devices. In fact I didn't even have a known_devices.yaml until adding Bermuda. It seems Bermuda may be using a legacy method.

The device_trackers are **very** useful. They provided a simple condition to verify a device is at home or not, so if they are at home then further actions can take place depending on area and distance. The device_tracker entity is much more stable than the area/distance which can swap areas (of course) but also frequently go `unknown` depending on signal level.

My addition of the Eve was just for testing, as I can pick it up and move around to see area and distance responses, much harder to do with the cars. I can also test with an iPhone MAC obtained from `current_address` in `Private BLE`, but only for about 5-15 minutes until it changes, a bit troublesome.

I'll see if I can create a `device_tracker.py` based off the `Private BLE Device` (`iBeacon` is horribly unreliable so don't want to use that) integration and do a PR if I can get it working.

**Comment by agittins** [comment]
That's a great help spotting the `device_tracker.py` in the Private BLE Device integration, I was never confident cribbing from elsewhere because the whole device_tracker feature felt out of date (to my eyes), but leaning on jc2k's work feels more reliable to me.

Have you had any luck with this so far? If you haven't had a chance to get into it I might jump into it shortly, but let me know if you've already sunk some time into it.

**Comment by jaymunro** [comment]
No sorry, haven't had too much of a chance and to be frank it's all quite new to me too. Most time so far has been spent trying to set up a dev environment for testing the builds so as not to affect my production environment.

I almost had one ready and then stuffed up my production env with an sql update and had to turn my dev env to production. Yada yada...

Long story short, yes go ahead with jumping into it and I'll try to help out where I can. I felt it was a steep curve getting to an understanding of what you had done and why so hadn't jumped in. Following you and helping out may work better.

**Comment by agittins** [comment]
This should now be fixed in #84 (included in release v0.4.3).

You'll need to fix any automations or other references to the old names, or rename the new entities to match.

Let me know how it goes when you have a chance, I'll leave this open until you have a chance to verify.

**Comment by jaymunro** [comment]
As I mentioned in #84, This seems to be working well for me too. I have changed my automations and UI to use the updated and much more user friendly names. Excellent job and a big thank you!

Does this lead to a clearer path toward getting private_ble method of resolving changing ble addresses? Once this happens, it will really result in devices being able to be tracked between areas and then being able to be refined for reliable tracking.

My hope then is that I can get an automation that triggers when someone is approaching the gate and turns on the gate light and opens the gate. 

I already have this working reliably for when cars come home (ble tracker changes from `away` to `home`) and it may now be possible for it to work when changing from garage to gate (until now too many `unknown` states).

With BLE private resolvable key working, I could potentially get this working for people too.

P.S. I have been getting quite a number of "device has changed TX power, this is unexpected" log entries. Just a heads up due to your comment in the source.

**Comment by agittins** [comment]
> This seems to be working well for me too

Awesome!

> Does this lead to a clearer path toward getting private_ble

Slightly, but not much. The next main *feature* I want to implement is private ble (#44), while the next main *bug* is the odd behaviour I see when freshly booting (#63 ) - and I suspect that both those things share some issues and will require me to sort out some oddities I might be introducing with respect to unique_id's and how I create the entities on start-up.

> when changing from garage to gate

Static MAC devices can already work for this, but it's worth keeping in mind even when we get IRK that spurious "area changes" are still common, as I'm still tweaking the method to decide if a beacon has really moved to a new area, or if the previous proxy has simply missed a (few) packet(s) and now it *looks* like it's in a new area. For lights this is not such a big issue, but for gates or doors you need a fairly high level of confidence. There's a tradeoff between confidence and responsiveness, but I think you could have it pretty reliable by having an automation check both the area and the distance - errors will always appear further away, so if it looks close you can be more confident.

I've been using my watch (which has a stable MAC address) to automate my office lights and front yard lights for a while with good results. For the office I use a PIR sensor for quick response and then Bermuda keeps the lights on even if I'm not moving (occasionally bermuda will turn on the lights as I approach the room before the PIR sees me, which is nice - but it's a dice-roll as to whether the advertisement arrives at a suitable time). 

Anyway, I'll mark this as resolved and move forward :-) Thanks for the prompt testing. 👍🏼
