### ISSUE TITLE
Some devices stop updating, likely due to BLE devices that don't always include their name.

### ISSUE THREAD

**Issue by agittins** [agittins/bermuda#63]
Running #5b25fdc I have just started encountering an issue where my Infinitime watch no longers updates the Area or Distance sensors configured for it.

My current theory is that the way I try to keep the device named using the `local_name` is causing an issue, possibly due to infinitime only sometimes sending the name (I think it does so when active scanning is on, ie the host sends a scan info request).

I'm back to waving my arms around to trigger the PIR because Bermuda isn't triggering the lights any more :-)

**Comment by jaymunro** [comment]
I recall something in iBeacon where a change in the core bluetooth code was made to ignore devices with no name in order to avoid random registrations of new devices from people walking by.

**Comment by jaymunro** [comment]
As best I can tell, https://github.com/home-assistant/core/pull/81599 the code is in the actual iBeacon integration and not a core library so unlikely to be the cause here.

**Comment by agittins** [comment]
Yeah, I'm familiar with that issue but it's unrelated to this one. Ironically, I think the issue is related to the way that I capture all devices seen, but only create entities for ones the user chooses - so in effect, I'm having this bug because I have a non-standard implementation that avoids the issue that iBeacon's treatment of the issue was designed to avoid, lol. But the code responsible and the mechanisms are otherwise unrelated.

**Comment by agittins** [comment]
I believe this is now fixed with #107
